
// Copyright 2021 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../api/video/video_codec_type.h

package org.webrtc;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    VideoCodecType.VIDEO_CODEC_GENERIC, VideoCodecType.VIDEO_CODEC_VP8,
    VideoCodecType.VIDEO_CODEC_VP9, VideoCodecType.VIDEO_CODEC_AV1, VideoCodecType.VIDEO_CODEC_H264,
    VideoCodecType.VIDEO_CODEC_MULTIPLEX
})
@Retention(RetentionPolicy.SOURCE)
public @interface VideoCodecType {
  /**
   * There are various memset(..., 0, ...) calls in the code that rely on VIDEO_CODEC_GENERIC being
   * zero.
   */
  int VIDEO_CODEC_GENERIC = 0;
  int VIDEO_CODEC_VP8 = 1;
  int VIDEO_CODEC_VP9 = 2;
  int VIDEO_CODEC_AV1 = 3;
  int VIDEO_CODEC_H264 = 4;
  int VIDEO_CODEC_MULTIPLEX = 5;
}
